include sys/sysmacros.h
glibc 2.28+ does not include this header implicitly via other system
headers anymore

src/devicescan.c:373: undefined reference to `makedev'

Signed-off-by: Khem Raj <raj.khem@gmail.com>